/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
}

version = "1.0.0"

val displayName = "vertx-starter"
val mainClass = "vertx.starter.App"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("commons-io:commons-io:2.6")
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("io.vertx:vertx-core:4.2.7")
    implementation("io.vertx:vertx-mysql-client:4.2.7")
    implementation("mysql:mysql-connector-java:8.0.28")

}

application {
    // Define the main class for the application.
    mainClass.set("vertx.starter.App")
}

java {
    withSourcesJar()
    withJavadocJar()
}

tasks.register<Jar>("uberJar") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveClassifier.set("uber")
    from(sourceSets.main.get().output)
    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
    })
    manifest {
        attributes(mapOf(
                "Implementation-Title" to displayName,
                "Implementation-Version" to project.version,
                "Main-Class" to mainClass,
        ))
    }
}