/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vertx.starter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertTrue(classUnderTest.getGreeting());
    }
}
